language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
after_success:
  - mkdir ~/.groovy
  - cp -f remote-test/src/test/resources/grapeConfig.xml ~/.groovy
  - mvn -e clean test jacoco:report coveralls:report
