language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
after_success:
  - mkdir ~/.groovy
  - cp -f remote-test/src/test/resources/grapeConfig.xml ~/.groovy
  - mkdir -p ~/.m2
  - cp -f dist/settings.xml ~/.m2
  - sed -i -e "s/BINTRAY_USER/${BINTRAY_USER}/g" -e "s/BINTRAY_API_KEY/${BINTRAY_API_KEY}/g" ~/.m2/settings.xml
  - mvn -e clean deploy jacoco:report coveralls:report
